Cookies disclaimer
actum/gulp-dev-stack pull request #102
Opened 2016-11-29 14:12 UTC by vbulant

https://github.com/actum/gulp-dev-stack/issues/82
@zoltan-kovac works on *accordion* module so let’s keep the issue open

2016-11-29 14:13 UTC, vbulant commented
CookieLaw fn is definitely useful, but it’s not the best example of factory functions (in fact, it’s not a factory function :).

Hope accordion will be better example.

2016-11-30 13:03 UTC, janpanschab requested changes

2016-11-30 13:03 UTC, janpanschab commented on src/styles/critical.scss
> +.hidden {
Use `.u-hidden` as a utility class or create cookie-law component with BEM.

2016-11-30 13:03 UTC, janpanschab commented on src/tpl/layouts/default.nunj
> +    {% include "../partials/cookie-law.nunj" %}
I don’t like partials here. It's time to remove it. It tends to use structure folder as container of all partials. I would suggest `tpl/component(s)/cookie-law.nunj`.

2016-11-30 13:03 UTC, janpanschab commented on src/tpl/partials/cookie-law.nunj
> +<p class="alert alert-info pos-f-t hidden" id="cookie-law" role="alert">
Indentation 4 instead 2.

2016-11-30 21:49 UTC, janpanschab approved these changes

2016-11-30 21:50 UTC, merged