SVG sprites: Proper bundling, Nunjucks "svg" macro
actum/gulp-dev-stack pull request #109
Opened 2016-12-07 14:18 UTC by kettanaito

The following changes were implemented:
* **Changed the logic behind globbing SVG sprites:** now we analyze nested folders under `${SVG_BASE}` and build the object in format `{ name: 'icons', glob: '/gfx/svg/icons/*.svg' }`. Then the same Gulp task runs through each collected object/sprite. This provides better control over globbing.
* Adjusted `svg()` macro in Nunjucks to be able to use it with default sprite (`icons` by default) or custom sprite for the projects were it is possible to have 2+ sprite bundles
* Added commentary to macro and `icons.nunj` pages, explaining the usage of the macro
* Uploaded new SVG icons for demonstration purpose

2016-12-08 09:29 UTC, janpanschab requested changes

2016-12-08 09:29 UTC, janpanschab commented on gulp/tasks/svg.js
> +    var sprites = [];
Should be possible use const here.

2016-12-08 09:29 UTC, janpanschab commented on gulp/tasks/svg.js
> +    spriteFolders.map((spriteName) => {
Use `.forEach` if you are not creating new array.

2016-12-08 12:02 UTC, janpanschab commented on gulp/tasks/svg.js
> +    return sprites.forEach(sprite => bundle(sprite));
Should’t we merge the streams here? Or, is it OK to return `sprites`?
But if it works...
@vbulant

2016-12-09 00:07 UTC, vbulant commented on gulp/tasks/svg.js
> +    return sprites.forEach(sprite => bundle(sprite));
Good idea. I don’t have that much experience with streams, but I’d give it a try.
Another suggestion: when you use forEach or similar higher order functions, you can do just
```js
sprites.forEach(bundle);
```

2016-12-09 14:40 UTC, janpanschab approved these changes

2016-12-09 14:41 UTC, janpanschab commented
I’ve already approved this PR? Do we want to merge it now?

2016-12-12 11:50 UTC, vbulant commented
Well then I’d merge it.

2016-12-12 15:51 UTC, merged