Api documentation
actum/gulp-dev-stack pull request #126
Opened 2017-01-27 06:29 UTC by janpanschab

close #66

2017-02-02 09:33 UTC, vbulant requested changes

2017-02-02 09:33 UTC, vbulant commented on README.md
> +#### Api sever
Api sever → API server (or maybe API mock)?

2017-02-03 09:47 UTC, vbulant requested changes

2017-02-03 09:47 UTC, vbulant commented on README.md
> +#### API mock sever
There’s still a minor typo: **sever** → **server**.

2017-02-03 10:22 UTC, janpanschab commented on README.md
> +#### API mock sever
Sorry jako

2017-02-03 10:34 UTC, vbulant approved these changes

2017-02-07 09:42 UTC, merged